import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// styling
import { Divider } from "@mui/material";
import "./Footer.scss";
// component
import { Link } from "react-router-dom";
export default function Footer() {
    return (_jsxs("footer", { className: "footer", children: [_jsxs("section", { className: "footer__contact", children: [_jsxs("div", { className: "footer__contact-wrapper", children: [_jsx("h4", { className: "footer__header", children: "Contact Us" }), _jsx("h5", { className: "footer__subheader", children: "Join us today!" }), _jsx("p", { className: "footer__text", children: "Got passion? Got purpose? Let's take on some projects and make an impact together." })] }), _jsx("div", { className: "footer__subscribe", children: _jsx("iframe", { className: "footer__substack", src: "https://versebuilding.substack.com/embed" }) })] }), _jsxs("section", { className: "footer__nav", children: [_jsxs("div", { className: "nav__the-verse", children: [_jsx("h4", { className: "nav__header", children: "The Verse" }), _jsx("ul", { className: "nav__list", children: _jsx(Link, { className: "nav__link", to: "/experiences", children: "Games & Digital Experiences" }) })] }), _jsxs("div", { className: "nav__information", children: [_jsx("h4", { className: "nav__header", children: "Information" }), _jsxs("ul", { className: "nav__list", children: [_jsx("li", { className: "nav__item", children: _jsx(Link, { to: "/privacy", className: "nav__link", children: "Privacy" }) }), _jsx("li", { className: "nav__item", children: _jsx(Link, { to: "/terms", className: "nav__link", children: "Terms" }) })] })] }), _jsxs("div", { className: "nav__resources", children: [_jsx("h4", { className: "nav__header", children: "Resources" }), _jsx("ul", { className: "nav__list", children: _jsx("li", { className: "nav__item", children: _jsx(Link, { to: "/contact-us", className: "nav__link", children: "Contact" }) }) })] }), _jsxs("div", { className: "nav__support", children: [_jsx("h4", { className: "nav__header", children: "Support" }), _jsx("ul", { className: "nav__list", children: _jsx("li", { className: "nav__item", children: _jsx(Link, { to: "/donate", className: "nav__link--donate", children: "Donate" }) }) })] })] }), _jsx(Divider, { sx: {
                    backgroundColor: "#AEB3B7",
                    margin: "1rem 0"
                } }), _jsxs("section", { className: "footer__wrapper", children: [_jsxs("div", { className: "footer__social", children: [_jsx("a", { href: "https://www.x.com/buildingverses", target: "_blank", children: _jsx("img", { className: "footer__social-icon", src: "/assets/logos/x.png", alt: "X" }) }), _jsx("a", { href: "https://www.instagram.com/buildingverses/", target: "_blank", children: _jsx("img", { className: "footer__social-icon", src: "/assets/logos/instagram.svg", alt: "Instagram" }) }), _jsx("a", { href: "https://www.linkedin.com/company/building-the-verse/", target: "_blank", children: _jsx("img", { className: "footer__social-icon", src: "/assets/logos/linkedin.png", alt: "LinkedIn" }) })] }), _jsx("p", { className: "footer__copyright", children: "Copyright \u00A9 The Verse 2024" })] })] }));
}
;
